server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
    driverClassName: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "+iU0MMdDPjqve7sSFU2+ZyiefWanNDaQc27uK5q3r/6uBnBrzK+1jGNd36+tOd6q"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in seconds

